clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  build:
    image: node:12-alpine
    commands:
      - npm install
      - npm run build
    when:
      event: [push, tag, pull_request]

  latest_docs:
    image: asciidoctor/docker-asciidoctor
    commands:
      - ./docs/docs.sh latest
    when:
      event: [push]

  release_docs:
    image: asciidoctor/docker-asciidoctor
    commands:
      - ./docs/docs.sh ${DRONE_TAG}
    when:
      event: [tag]

  moon_website_latest_image:
    image: plugins/docker
    registry: registry.aerokube.com
    repo: registry.aerokube.com/moon-ru/website
    secrets: [ docker_username, docker_password ]
    tags: [ 'latest' ]
    when:
      branch: master
      event: push

  moon_website_release_image:
    image: plugins/docker
    registry: registry.aerokube.com
    repo: registry.aerokube.com/moon-ru/website
    secrets: [ docker_username, docker_password ]
    tags: [ '${DRONE_TAG}', 'latest-release' ]
    when:
      event: tag
