name: release

on:
  release:
    types: [published]

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Prepare release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Build
        run: ci/build.sh $RELEASE_VERSION

      - name: Docs
        env:
          S3_ENDPOINT: ${{ secrets.YC_S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.YC_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.YC_REGION }}
        run: ci/docs.sh $RELEASE_VERSION

      - name: Release image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ci/docker-push.sh $RELEASE_VERSION
